package entity

import (
	"time"
)

type AutoGenerated struct {
	Status struct {
		Timestamp    time.Time   `json:"timestamp"`
		ErrorCode    int         `json:"error_code"`
		ErrorMessage interface{} `json:"error_message"`
		Elapsed      int         `json:"elapsed"`
		CreditCount  int         `json:"credit_count"`
		Notice       interface{} `json:"notice"`
	} `json:"status"`
	Data struct {
		BTC struct {
			Symbol      string    `json:"symbol"`
			ID          string    `json:"id"`
			Name        string    `json:"name"`
			Amount      int       `json:"amount"`
			LastUpdated time.Time `json:"last_updated"`
			Quote       struct {
				USD struct {
					Price       int       `json:"price"`
					LastUpdated time.Time `json:"last_updated"`
				} `json:"USD"`
				EUR struct {
					Price       int       `json:"price"`
					LastUpdated time.Time `json:"last_updated"`
				} `json:"EUR"`
			} `json:"quote"`
		} `json:"BTC"`
	} `json:"data"`
}
